// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeenJeemGame.Infrastructure.Persistence;

#nullable disable

namespace SeenJeemGame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611053109_AddTrapToGameTurn")]
    partial class AddTrapToGameTurn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.AnswerAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("GameTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecondChance")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameTurnId", "TeamId");

                    b.ToTable("AnswerAttempts");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "دين"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "جغرافيا"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "تاريخ"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "كورة"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "رياضيات"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "معلومات عامة"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "أفلام ومسلسلات"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "علوم"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "تكنولوجيا"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ألغاز"
                        });
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameSessionId", "CategoryId")
                        .IsUnique();

                    b.HasIndex("GameSessionId", "Order")
                        .IsUnique();

                    b.ToTable("GameCategories");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsedByTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("GameSessionId", "QuestionId")
                        .IsUnique();

                    b.HasIndex("GameSessionId", "CategoryId", "Difficulty");

                    b.ToTable("GameQuestions");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MainTeamTimerSeconds")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SecondTeamTimerSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasePoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("GameQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDoublePointsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStopPlayerUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrapUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoAnswersUsed")
                        .HasColumnType("bit");

                    b.Property<Guid>("MainTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SecondTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StoppedPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrapTargetTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameQuestionId")
                        .IsUnique();

                    b.HasIndex("GameSessionId");

                    b.HasIndex("MainTeamId");

                    b.HasIndex("SecondTeamId");

                    b.ToTable("GameTurns");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStoppedForCurrentQuestion")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Difficulty");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.ScoreTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameTurnId");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameSessionId", "TeamId");

                    b.ToTable("ScoreTransactions");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId", "Name")
                        .IsUnique();

                    b.HasIndex("GameSessionId", "TurnOrder")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.TeamHelpOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsedInTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Type")
                        .IsUnique();

                    b.ToTable("TeamHelpOptions");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.AnswerAttempt", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.GameTurn", "GameTurn")
                        .WithMany("AnswerAttempts")
                        .HasForeignKey("GameTurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameTurn");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameCategory", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.GameSession", "GameSession")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameQuestion", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.GameSession", "GameSession")
                        .WithMany("GameQuestions")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("GameSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameTurn", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.GameQuestion", "GameQuestion")
                        .WithMany()
                        .HasForeignKey("GameQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Turns")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.Team", "MainTeam")
                        .WithMany()
                        .HasForeignKey("MainTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.Team", "SecondTeam")
                        .WithMany()
                        .HasForeignKey("SecondTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameQuestion");

                    b.Navigation("GameSession");

                    b.Navigation("MainTeam");

                    b.Navigation("SecondTeam");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Player", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Question", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.ScoreTransaction", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.GameTurn", "GameTurn")
                        .WithMany()
                        .HasForeignKey("GameTurnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SeenJeemGame.Domain.Entities.Team", "Team")
                        .WithMany("ScoreTransactions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("GameTurn");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Team", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Teams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.TeamHelpOption", b =>
                {
                    b.HasOne("SeenJeemGame.Domain.Entities.Team", "Team")
                        .WithMany("HelpOptions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("GameCategories");

                    b.Navigation("GameQuestions");

                    b.Navigation("Teams");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.GameTurn", b =>
                {
                    b.Navigation("AnswerAttempts");
                });

            modelBuilder.Entity("SeenJeemGame.Domain.Entities.Team", b =>
                {
                    b.Navigation("HelpOptions");

                    b.Navigation("Players");

                    b.Navigation("ScoreTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
